# Site wide configuration

title: "Olimpíada de Matemática do Oeste Catarinense"
description: "Realização da Universidade Federal da Fronteira Sul, Chapecó, SC, Brasil."
nav-logo: /common/omoc-nav-icon-width-140.png
root-path: /
url: https://omoc.uffs.edu.br
# Jekyll configuration
permalink: pretty
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: default

include:
  - _pages

colections:
  edicoes-anteriores:
    output: true
